[workspace]
resolver = "3"

members = [
	"main", "snake",
]


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"] } # DEV
# bevy = { version = "0.16.1" } # RELEASE