[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
getrandom = { version = "0.3.3", features = ["wasm_js"] }
rand = "0.9.1"

[features]
dynamic = ["bevy/dynamic_linking"] # for development
