[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[build.release]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

[alias]
build-dyn = "build --features dynamic"
